<?php
include_once('..//..//..//wp-config.php');
include_once('..//..//..//wp-admin//includes//file.php');

$id = $_POST['id'];
$p = $_POST['p'];
$t = $_POST['t'];

$my_post = array(
  'post_title'    => $t,
  'post_content'  => $p,
  'ID'            => $id
);

// Insert the post into the database
wp_update_post( $my_post );

// $filename should be the path to a file in the upload directory.
//$filename = '2015//04//Lavapiatti.jpg';

$uploadedfile = $_FILES['file'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

$filename = $movefile['file'];
if ( $movefile && !isset( $movefile['error'] ) ) {
    echo "File is valid, and was successfully uploaded.\n";
    
    // Check the type of file. We'll use this as the 'post_mime_type'.
    $filetype = wp_check_filetype( basename( $filename ), null );

    // Get the path to the upload directory.
    $wp_upload_dir = wp_upload_dir();

    // Prepare an array of post data for the attachment.
    $attachment = array(
	    'guid'           => $wp_upload_dir['url'] . '/' . basename( $filename ), 
	    'post_mime_type' => $filetype['type'],
	    'post_title'     => preg_replace( '/\.[^.]+$/', '', basename( $filename ) ),
	    'post_content'   => '',
	    'post_status'    => 'inherit'
    );

    // Insert the attachment.
    $attach_id = wp_insert_attachment( $attachment, $filename, $id );

    // Make sure that this file is included, as wp_generate_attachment_metadata() depends on it.
    require_once( ABSPATH . 'wp-admin/includes/image.php' );

    // Generate the metadata for the attachment, and update the database record.
    $attach_data = wp_generate_attachment_metadata( $attach_id, $filename );
    wp_update_attachment_metadata( $attach_id, $attach_data );
    set_post_thumbnail( $my_post, $attach_id);

} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}

?>